server:
  port: 8888
  
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:E:/fangwenzheng/springcloud/configRepo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
